apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rulegroups.config.prometheus.io
spec:
  group: config.prometheus.io
  scope: Namespaced
  names:
    kind: RuleGroup
    plural: rulegroups
    singular: rulegroup
    shortNames:
    - prgs
    - prg
  versions:
  - name: v1beta1
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      type: object
      required:
      - spec
      properties:
        spec:
          type: object
          required:
          - rules
          properties:
            interval:
              type: string
            rules:
              type: array
              items:
                type: object
                required:
                - expr
                properties:
                  expr:
                    type: string
                  labels:
                    type: object
                    additionalProperties:
                      type: string
                  annotations:
                    type: object
                    additionalProperties:
                      type: string
                  alert:
                    type: string
                  for:
                    type: string
                  record:
                    type: string
        status:
          type: object
          properties:
            errors:
              type: array
              items:
                type: string
  subresources:
    status: {}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: scrapes.config.prometheus.io
spec:
  group: config.prometheus.io
  version: v1beta1
  scope: Namespaced
  names:
    kind: Scrape
    plural: scrapes
    singular: scrape
    shortNames:
    - pscs
    - psc
  versions:
  - name: v1beta1
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: string
      required:
      - spec
