apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prom-config-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - "config.prometheus.io"
  resources:
  - rulegroups
  - scrapes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prom-config-edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - "config.prometheus.io"
  resources:
  - rulegroups
  - scrapes
  verbs:
  - get
  - list
  - watch
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prom-config-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - "config.prometheus.io"
  resources:
  - rulegroups
  - scrapes
  verbs:
  - "*"

