/*
Copyright 2022 The Kubernetes sample-controller Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	configv1beta1 "github.com/QubitProducts/prom-config-controller/pkg/apis/config/v1beta1"
	versioned "github.com/QubitProducts/prom-config-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/QubitProducts/prom-config-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/QubitProducts/prom-config-controller/pkg/client/listers/config/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ScrapeInformer provides access to a shared informer and lister for
// Scrapes.
type ScrapeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.ScrapeLister
}

type scrapeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewScrapeInformer constructs a new informer for Scrape type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewScrapeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredScrapeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredScrapeInformer constructs a new informer for Scrape type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredScrapeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ConfigV1beta1().Scrapes(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ConfigV1beta1().Scrapes(namespace).Watch(context.TODO(), options)
			},
		},
		&configv1beta1.Scrape{},
		resyncPeriod,
		indexers,
	)
}

func (f *scrapeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredScrapeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *scrapeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&configv1beta1.Scrape{}, f.defaultInformer)
}

func (f *scrapeInformer) Lister() v1beta1.ScrapeLister {
	return v1beta1.NewScrapeLister(f.Informer().GetIndexer())
}
